
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMP BEGIN CAP CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHFOUR CLOSEHREF CLOSEROW CLOSESMALL CLOSESPAN CLOSESTYLE CLOSETABLE CLOSETBODY CONTENT ENTITY FALTU GARBAGE IMG OPENDATA OPENDIV OPENHEADER OPENHFOUR OPENHREF OPENROW OPENSMALL OPENSPAN OPENSTYLE OPENTABLE OPENTBODYstart : BEGIN skipall OPENTBODY content_rec handle_row CLOSETBODYhandle_row : OPENROW content_rec OPENDATA content_rec CLOSEDATA content_rec recurse_td CLOSEROW content_rec handle_row\n                    | empty recurse_td : OPENDATA content_rec CLOSEDATA content_rec recurse_td\n                    | emptyskipall : CONTENT skipall\n                | OPENDATA skipall\n                | CLOSEDATA skipall\n                | OPENROW  skipall\n                | CLOSEROW skipall\n               | emptycontent_rec : CONTENT content_rec\n                    | emptyempty :'
    
_lr_action_items = {'BEGIN':([0,],[2,]),'$end':([1,23,],[0,-1,]),'CONTENT':([2,4,5,6,7,8,10,17,20,25,27,29,33,34,],[4,4,4,4,4,4,17,17,17,17,17,17,17,17,]),'OPENDATA':([2,4,5,6,7,8,17,18,20,22,24,27,28,34,36,],[5,5,5,5,5,5,-14,-13,-14,-12,25,-14,29,-14,29,]),'CLOSEDATA':([2,4,5,6,7,8,17,18,22,25,26,29,32,],[6,6,6,6,6,6,-14,-13,-12,-14,27,-14,34,]),'OPENROW':([2,4,5,6,7,8,10,16,17,18,22,33,35,],[7,7,7,7,7,7,-14,20,-14,-13,-12,-14,20,]),'CLOSEROW':([2,4,5,6,7,8,17,18,22,27,28,30,31,34,36,38,],[8,8,8,8,8,8,-14,-13,-12,-14,-14,33,-5,-14,-14,-4,]),'OPENTBODY':([2,3,4,5,6,7,8,9,11,12,13,14,15,],[-14,10,-14,-14,-14,-14,-14,-11,-6,-7,-8,-9,-10,]),'CLOSETBODY':([10,16,17,18,19,21,22,33,35,37,],[-14,-14,-14,-13,23,-3,-12,-14,-14,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'skipall':([2,4,5,6,7,8,],[3,11,12,13,14,15,]),'empty':([2,4,5,6,7,8,10,16,17,20,25,27,28,29,33,34,35,36,],[9,9,9,9,9,9,18,21,18,18,18,18,31,18,18,18,21,31,]),'content_rec':([10,17,20,25,27,29,33,34,],[16,22,24,26,28,32,35,36,]),'handle_row':([16,35,],[19,37,]),'recurse_td':([28,36,],[30,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> BEGIN skipall OPENTBODY content_rec handle_row CLOSETBODY','start',6,'p_start','3_1.py',80),
  ('handle_row -> OPENROW content_rec OPENDATA content_rec CLOSEDATA content_rec recurse_td CLOSEROW content_rec handle_row','handle_row',10,'p_handle_row','3_1.py',84),
  ('handle_row -> empty','handle_row',1,'p_handle_row','3_1.py',85),
  ('recurse_td -> OPENDATA content_rec CLOSEDATA content_rec recurse_td','recurse_td',5,'p_recurse_td','3_1.py',91),
  ('recurse_td -> empty','recurse_td',1,'p_recurse_td','3_1.py',92),
  ('skipall -> CONTENT skipall','skipall',2,'p_skipall','3_1.py',104),
  ('skipall -> OPENDATA skipall','skipall',2,'p_skipall','3_1.py',105),
  ('skipall -> CLOSEDATA skipall','skipall',2,'p_skipall','3_1.py',106),
  ('skipall -> OPENROW skipall','skipall',2,'p_skipall','3_1.py',107),
  ('skipall -> CLOSEROW skipall','skipall',2,'p_skipall','3_1.py',108),
  ('skipall -> empty','skipall',1,'p_skipall','3_1.py',109),
  ('content_rec -> CONTENT content_rec','content_rec',2,'p_content_rec','3_1.py',113),
  ('content_rec -> empty','content_rec',1,'p_content_rec','3_1.py',114),
  ('empty -> <empty>','empty',0,'p_empty','3_1.py',124),
]
