
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN CLOSE_H3 CLOSE_H4 CONTENT END OPEN_H3 OPEN_H4start : tableskiptag : CONTENT skiptag\n               | emptytable : BEGIN skiptag data skiptag ENDdate : OPEN_H4 CONTENT content CLOSE_H4month : OPEN_H3 CONTENT content CLOSE_H3elements : elements date content\n                | date contentempty :data : data month elements\n            | month elementscontent : CONTENT content\n               | empty'
    
_lr_action_items = {'BEGIN':([0,],[3,]),'$end':([1,2,17,],[0,-1,-4,]),'CONTENT':([3,5,7,9,13,14,15,16,18,19,20,21,22,23,25,26,29,],[5,5,5,16,-11,21,23,21,-10,21,-8,21,-13,21,-7,-12,-5,]),'OPEN_H3':([3,4,5,6,7,10,13,14,18,19,20,21,22,25,26,29,],[-9,9,-9,-3,9,-2,-11,-9,-10,-9,-8,-9,-13,-7,-12,-5,]),'END':([5,6,7,10,11,13,14,18,19,20,21,22,25,26,29,],[-9,-3,-9,-2,17,-11,-9,-10,-9,-8,-9,-13,-7,-12,-5,]),'OPEN_H4':([8,12,13,14,18,19,20,21,22,25,26,28,29,],[15,15,15,-9,15,-9,-8,-9,-13,-7,-12,-6,-5,]),'CLOSE_H3':([16,21,22,24,26,],[-9,-9,-13,28,-12,]),'CLOSE_H4':([21,22,23,26,27,],[-9,-13,-9,-12,29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,7,],[4,10,11,]),'empty':([3,5,7,14,16,19,21,23,],[6,6,6,22,22,22,22,22,]),'data':([4,],[7,]),'month':([4,7,],[8,12,]),'elements':([8,12,],[13,18,]),'date':([8,12,13,18,],[14,14,19,19,]),'content':([14,16,19,21,23,],[20,24,25,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','2023_2024_util.py',51),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','2023_2024_util.py',55),
  ('skiptag -> empty','skiptag',1,'p_skiptag','2023_2024_util.py',56),
  ('table -> BEGIN skiptag data skiptag END','table',5,'p_table','2023_2024_util.py',60),
  ('date -> OPEN_H4 CONTENT content CLOSE_H4','date',4,'p_date','2023_2024_util.py',65),
  ('month -> OPEN_H3 CONTENT content CLOSE_H3','month',4,'p_month','2023_2024_util.py',74),
  ('elements -> elements date content','elements',3,'p_elements','2023_2024_util.py',82),
  ('elements -> date content','elements',2,'p_elements','2023_2024_util.py',83),
  ('empty -> <empty>','empty',0,'p_empty','2023_2024_util.py',94),
  ('data -> data month elements','data',3,'p_data','2023_2024_util.py',98),
  ('data -> month elements','data',2,'p_data','2023_2024_util.py',99),
  ('content -> CONTENT content','content',2,'p_content','2023_2024_util.py',109),
  ('content -> empty','content',1,'p_content','2023_2024_util.py',110),
]
